return {
  copy = "%c | wl-copy",
  silent = false,
  use_current_theme = true,
  author = "Apika Luca",
  window_controls = true,
  window_controls_height = 30,
  fonts = "Miracode Nerd Font=24.0",
  -- background = require("apika.theme.colors").term_background,
  background = "#121212",
  shadow = true,
  shadow_color = "#121212",
  shadow_blur = 30,
  padding_x = 50,
  padding_y = 70,
}
